### ISSUE TITLE
Missing search functionality

### ISSUE THREAD

**Issue by LenzGr** [westerndigitalcorporation/zonedstorage.io#47]
The new zonedstorage.io web site powered by [Docusaurus](https://docusaurus.io/) is missing a search functionality. It would be nice to have an easy way to search the documentation for keywords. Docusaurus provides [several search options](https://docusaurus.io/docs/search) for implementing this.

**Comment by damien-lemoal** [comment]
I know. I registered with Algolia DocSearch and I am waiting to get the site ID back. Once I get that, I will enable the search box. The site had to go up first so that Algolia DocSearch can crawl it.

**Comment by damien-lemoal** [comment]
Search added.
